import fs from "node:fs/promises";
import path from "node:path";

/**
 * Build a Caddyfile snippet that 301-redirects each old URL to the canonical
 * Indiekit URL. Designed to be imported from the user's main Caddyfile via:
 *
 *   import /etc/caddy/migration-redirects
 *
 * The snippet itself contains only `redir` directives — no site block — so it
 * inherits the surrounding scope.
 */
export function renderCaddyfile(redirects) {
  const lines = [
    "# Generated by indiekit-deploy migration tool — do not edit by hand.",
    "# Import this from your main Caddyfile inside the site block:",
    "#   import /etc/caddy/migration-redirects",
    "",
  ];
  for (const r of redirects) {
    if (!r.from || !r.to || r.from === r.to) continue;
    lines.push(`redir ${escapeCaddyToken(r.from)} ${escapeCaddyToken(r.to)} 301`);
  }
  return lines.join("\n") + "\n";
}

/**
 * Tokens with spaces are uncommon in URLs but defend against them anyway.
 * Caddy treats backslash and quote as escape characters in tokens.
 */
function escapeCaddyToken(token) {
  if (/^[A-Za-z0-9._~:/?#@!$&'()*+,;=%-]+$/.test(token)) return token;
  return `"${token.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export async function writeRedirectsFile(redirects, stagedRoot) {
  const dest = path.join(stagedRoot, "Caddyfile.redirects");
  await fs.writeFile(dest, renderCaddyfile(redirects), "utf8");
  return dest;
}
